packaging_format = 2

id = "xwiki"
name = "xWiki"
description.en = "Collaboration tool based on the wiki principle"
description.fr = "Outil de collaboration basé sur le principe du wiki"

version = "15.10~ynh1"

maintainers = [""]

[upstream]
license = "LGPL-2.1"
website = "https://www.xwiki.org/"
demo = "https://playground.xwiki.org/xwiki/bin/view/Main/WebHome"
admindoc = "https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/"
userdoc = "https://www.xwiki.org/xwiki/bin/view/Documentation/UserGuide/"
code = "https://github.com/xwiki/xwiki-platform"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "500M"
ram.build = "0M"
ram.runtime = "1G"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/xwiki"

    [install.install_standard_flavor]
    ask.en = "Would you like to install the Standard Flavor ?"
    help.en = "See https://extensions.xwiki.org/xwiki/bin/view/Extension/XWiki%20Standard%20Flavor/ for more informations."
    type = "boolean"
    default = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.init_admin_permission]
    ask.en = "Which group will have access to xWiki admin page"
    ask.fr = "Quel groupe aura accès à l'administration de xWiki"
    help.en = "Users of this group should have access to xWiki admin page"
    help.fr = "Les utilisateurs de ce groupe devrait avoir accès à la page d'administration de xWiki"
    type = "group"
    default = "admins"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/platform/xwiki-platform-distribution-jetty-hsqldb/15.10.1/xwiki-platform-distribution-jetty-hsqldb-15.10.1.zip"
        sha256 = "76efd6e1c58b8557034a3e25271963392b8b5e125af97d932210823510586e9f"
        format = "zip"

        [resources.sources.jdbc]
        url = "https://jdbc.postgresql.org/download/postgresql-42.7.0.jar"
        rename = "postgresql-42.7.0.jar"
        sha256 = "90c39c97ac309b5767882f9beef913244da029204af2d2982c2b45bcfcb42624"

        # Note that xq is available on debian package since debian 12
        # So on bookworm should just remove this and use official package
        [resources.sources.xq_tool]
        in_subdir= false

        i386.url = "https://github.com/sibprogrammer/xq/releases/download/v1.2.3/xq_1.2.3_linux_386.tar.gz"
        i386.sha256 = "fc500e887d825f6cbedecdbfb3a272e1a88473b1f1a1b92075cab429d3d6fc64"

        amd64.url = "https://github.com/sibprogrammer/xq/releases/download/v1.2.3/xq_1.2.3_linux_amd64.tar.gz"
        amd64.sha256 = "d510d97a247ad9b5a4e92759ea9b1b6be07d9f18187209b359525744e1bb8947"

        armhf.url = "https://github.com/sibprogrammer/xq/releases/download/v1.2.3/xq_1.2.3_linux_armv7.tar.gz"
        armhf.sha256 = "f9b01ba7d77965f292f3c1b8c164267367507e16a8951b67733a539d7f73eecb"

        arm64.url = "https://github.com/sibprogrammer/xq/releases/download/v1.2.3/xq_1.2.3_linux_arm64.tar.gz"
        arm64.sha256 = "a8989b2b1a5254033aebacb72ffea77964d6903d809361001dbf1ed09a0c6550"

        #
        # INFO need also to update extensions version on _common.sh
        #

    [resources.ports]
    main.default = 8080

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    dir = "/home/yunohost.app/__APP__"

    [resources.permissions]
    main.url = "/"

    admin.label = "Admins"

    [resources.apt]
    packages = ["openjdk-17-jre", "postgresql"]

    [resources.database]
    type = "postgresql"
