packaging_format = 2

id = "xwiki"
name = "xWiki"
description.en = "Collaboration tool based on the wiki principle"
description.fr = "Outil de collaboration basé sur le principe du wiki"

version = "14.10.8~ynh1"

maintainers = [""]

[upstream]
license = "LGPL-2.1"
website = "https://www.xwiki.org/"
demo = "https://playground.xwiki.org/xwiki/bin/view/Main/WebHome"
admindoc = "https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/"
userdoc = "https://www.xwiki.org/xwiki/bin/view/Documentation/UserGuide/"
code = "https://github.com/xwiki/xwiki-platform"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/platform/xwiki-platform-distribution-jetty-hsqldb/14.10.8/xwiki-platform-distribution-jetty-hsqldb-14.10.8.zip"
        sha256 = "42bb11563587860d2268f3226b90c6ae5cf5930e027fe0e3386fb2de29445a2b"

    [resources.ports]
    main.default = 31386
    stop.default = 31387

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server openjdk-17-jdk"

    [resources.database]
    type = "mysql"
